version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "lerianstudio"
    # Specify labels for pull requests
    labels:
      - "dependencies"
    # Limit the number of open pull requests for version updates
    open-pull-requests-limit: 10
    # Allow up to 5 dependencies to be upgraded in a pull request
    pull-request-branch-name:
      separator: "-"
    # Group all development dependencies in a single PR
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "jest"
          - "ts-jest"
          - "typescript"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"