version: 2
updates:
  # NPM Dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 10
    assignees:
      - "fredamaral"
    reviewers:
      - "fredamaral"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    groups:
      typescript-ecosystem:
        patterns:
          - "typescript"
          - "@types/*"
          - "ts-*"
        update-types:
          - "minor"
          - "patch"
      testing-framework:
        patterns:
          - "jest"
          - "@types/jest"
          - "ts-jest"
        update-types:
          - "minor"
          - "patch"
      linting-tools:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"
        update-types:
          - "minor"
          - "patch"
      build-tools:
        patterns:
          - "typedoc"
          - "dotenv"
        update-types:
          - "minor"
          - "patch"
      runtime-dependencies:
        patterns:
          - "axios"
          - "pino*"
          - "abort-controller"
          - "node-fetch"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions Dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    assignees:
      - "fredamaral"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"