version: 2

# Define common settings using YAML anchors
x-common-schedule: &common_schedule
  interval: "weekly"
  day: "monday"
  time: "08:00"

x-common-assignees: &common_assignees
  - "fredamaral"

x-common-reviewers: &common_reviewers
  - "fredamaral"

updates:
  # NPM Dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      <<: *common_schedule
    open-pull-requests-limit: 10
    assignees: *common_assignees
    reviewers: *common_reviewers
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    groups:
      typescript-ecosystem:
        patterns:
          - "typescript"
          - "@types/*"
          - "ts-*"
        update-types:
          - "minor"
          - "patch"
      testing-framework:
        patterns:
          - "jest"
          - "@types/jest"
          - "ts-jest"
        update-types:
          - "minor"
          - "patch"
      linting-tools:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"
        update-types:
          - "minor"
          - "patch"
      build-tools:
        patterns:
          - "typedoc"
          - "dotenv"
        update-types:
          - "minor"
          - "patch"
      runtime-dependencies:
        patterns:
          - "axios"
          - "pino*"
          - "abort-controller"
          - "node-fetch"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions Dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      <<: *common_schedule
    open-pull-requests-limit: 10
    assignees: *common_assignees
    reviewers: *common_reviewers
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"