feature: ['feature/*', 'feat/*']
bug: ['bugfix/*', 'fix/*']
documentation: ['docs/*', 'doc/*']
enhancement: ['enhancement/*', 'improve/*']
maintenance: ['chore/*', 'maintenance/*']
refactor: ['refactor/*']
performance: ['perf/*', 'performance/*']
testing: ['test/*', 'testing/*']
style: ['style/*']
ci: ['ci/*', 'workflow/*']
dependencies: ['deps/*', 'dependencies/*']