blank_issues_enabled: false
contact_links:
  - name: Midaz SDK Documentation
    url: https://docs.lerian.studio
    about: Check the documentation for usage guidance
  - name: GitHub Discussions
    url: https://github.com/lerianstudio/midaz-sdk-typescript/discussions
    about: Please ask and answer questions here
