name: PR Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration-path: .github/pr-labeler.yml
